timdeschryver/eslint-plugin-ngrx

src/configs/recommended.json
src/rules/index.ts
src/rules/no-effect-decorator.ts
tests/rules/no-effect-decorator.test.ts

I put this one as an error whereas it is only a warning in ngrx-tslint-rule.
createEffect has been introduced 2 versions ago in NGRX (if I'm not mistaken) so I believe it is ok to put it as an error.
Users can still override the recommended config and put it as a warning if needed.
If you believe it should stay a warning, I can switch it back.

feat: adds no-effect-decorator rule

---

src/configs/recommended.json
src/rules/index.ts
src/rules/no-effects-in-providers.ts
src/rules/utils/selectors/index.ts
tests/rules/no-effects-in-providers.test.ts

This a basic migration from ngrx-tslint-rules but this rule can only detect errors if effects are imported and provided in the same file. So it won't catch a lot of errors but it's better than nothing.
I needed to wait for decorator:exit so that errors would be reported for the providers even if providers are defined before the imports.
I added an error test case to validate this point

feat: adds no-effects-in-providers rule

---

src/configs/recommended.json
src/rules/index.ts
src/rules/use-selector-in-select.ts
src/rules/utils/selectors/index.ts
tests/rules/use-selector-in-select.test.ts

This the migration of the TSLint rule `ngrx-selector-for-select`
I made a small name change that made more sense to me.
What do you think ?

feat: adds use-selector-in-select rule

---

src/configs/recommended.json
src/rules/index.ts
src/rules/on-function-explicit-return-type.ts
src/rules/utils/selectors/index.ts
tests/rules/on-function-explicit-return-type.test.ts

Here is the newly added rule.
I must say I am not a big fan of the rule name. "On reducer" makes me think we are talking about the reducer itself but that's not really the case.
I thought of something like "state-change-function-explicit-return-type" but it's a bit long and I don't know if everybody calls these functions "state change function". I found this name in NGRX documentation though.
"on-function-explicit-return-type" would be a bit clearer to me but we're still not typing the "on" function either.
As it was done on tslint repo, I didn't add the rule to the recommended config although I don't fully understand why we would not.

feat: adds on-reducer-explicit-return-type rule

---

src/configs/recommended.json
src/rules/index.ts
src/utils/selectors/index.ts
tests/rules/on-function-explicit-return-type.test.ts

The selector was not correct and reported an error when using immer produce function.

fix: do not report on-function-explicit-return-type error when using immer

---

docs/rules/select-style.md
src/rules/index.ts
src/rules/select-style.ts
src/utils/selectors/index.ts
tests/rules/store-select.test.ts
tests/rules/use-selector-in-select.test.ts

Add a rule to define how selectors should be used in the project.
This rule is not part of recommended configuration.
The default value is 'operator' because it seems to be the recommended way in NGRX documentation and it allows to use more advanced features: 
- [Make use of rxjs operators](https://ngrx.io/guide/store/selectors#select-a-non-empty-state-using-pipeable-operators)
- [Extracting a pipeable operator](https://ngrx.io/guide/store/selectors#solution-extracting-a-pipeable-operator)
For ease (and because I use the underlying modifications), I'm including in this branch the commit for #27. So the bug fix should probably be merged before this one

feat: add select-style rule

---

src/utils/selectors/index.ts
tests/rules/use-selector-in-select.test.ts

I realized use-selector-in-select rule would not throw when store is a class property which is always the case.

fix: throw error when store is a class property

---

package-lock.json
package.json
src/rules/index.ts
src/rules/no-multiple-actions-in-effects.ts
src/utils/helper-functions/index.ts
src/utils/selectors/index.ts
tests/rules/no-multiple-actions-in-effects.test.ts
tests/utils/index.ts
tsconfig.eslint.json

This rule's implementation gave me headaches... Working with types in ESLint is not that easy after all.
I didn't manage to check if the return is of type `Action[]` so I've only been looking for returned arrays in effects.
It covers all test cases that I found in ngrx-tslint-rules but I am not sure it will not report false positives.
What do you think?

feat: adds no-multiple-actions-in-effects rule

---

src/rules/avoid-dispatching-multiple-actions-sequentially.ts
src/rules/no-multiple-stores.ts
src/rules/use-selector-in-select.ts
src/utils/helper-functions/guards.ts
src/utils/selectors/index.ts
tests/rules/no-multiple-stores.test.ts
tests/rules/use-selector-in-select.test.ts

Closes #41
@jsaguet this is basically a re-write of the rule.
The rule also takes into account when the store is renamed to for example `store$`

fix(use-selector-in-select): allow parameters

---

scripts/generate-config.ts
src/configs/recommended.ts

The recent addition of the rxjs/no-cycle-action rule broke the recommended config.
Error message: Configuration for rule "rxjs/no-cyclic-action" is invalid:  Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"warning"').
This PR changes the level for this rule to a valid eslint value.

fix: level of rxjs/no-cyclic-action

---

package-lock.json
package.json

version update to solve https://github.com/cartant/eslint-plugin-rxjs/issues/54 issue.
I was wondering if peer dependency wouldn't be better to let the user select the version to use.
What do you think ?

fix: update eslint-plugin-rxjs version

---

src/rules/no-multiple-actions-in-effects.ts
src/utils/selectors/index.ts
tests/rules/no-multiple-actions-in-effects.test.ts

Fixes #61.
in addition to fix the error reported in #61, I also changed the selectors to search for the exact names, instead of part of them, to avoid a possible problem with custom operators and also added some more tests to cover for all operators in the context.

fix: no-multiple-actions-in-effects not reporting mapTo operators

---

src/rules/use-lifecycle-interface.ts
src/utils/helper-functions/guards.ts
src/utils/helper-functions/utils.ts
tests/rules/use-lifecycle-interface.test.ts

This PR aims to add a fixer for `use-lifecycle-interface`.
**Before**:
```ts
class UserEffects {
ngrxOnInitEffects() {}
}
```
**After (--fix)**:
```ts
import { OnInitEffects } from '@ngrx/effects';
class UserEffects implements OnInitEffects {
ngrxOnInitEffects() {}
}
```

feat: add fixer for use-lifecycle-interface

---

src/rules/no-typed-store.ts
tests/rules/no-typed-store.test.ts

This PR aims to add a ~fixer~ suggest (it can't be a fixer as it can produce invalid code as reported in https://github.com/ngrx/platform/issues/2780).

feat: add fixer for no-typed-store rule

---

scripts/generate-config.ts
src/rules/avoid-combining-selectors.ts
src/rules/avoid-mapping-selectors.ts
src/rules/no-dispatch-in-effects.ts
src/rules/select-style.ts
src/utils/helper-functions/index.ts
src/utils/helper-functions/settings.ts
src/utils/selectors/index.ts
tests/rules/select-style.test.ts

Storename is customizable via ESLint shared settings
@rafaelss95 what do you think?
I think this is the easiest way to allow a different name for `store` (or `store$`).
The harder way would be to get the store name at runtime and somehow query for "invalid" code, this would mean we can't use the esquery syntax anymore, as far as I know.

fix: lint for store or store$

---

src/rules/use-selector-in-select.ts
src/utils/helper-functions/guards.ts

I removed `isFunctionExpressionLike` and replaced it by `isArrowFunctionExpression(node) || isFunctionExpression(node)` in `use-selector-in-select.ts` as it was only used once and it's not the same as all other utilitites
---
Closes #81

refactor: extract `isNodeOfType` functions

---

docs/rules/select-style.md
src/rules/store/select-style.ts
tests/rules/select-style.test.ts

Define the preferred way with a string instead of an object.
BEFORE:
```json
"rules": {
"ngrx/select-style": ["warn", { "mode": "operator" }]
}
```
AFTER:
```json
"rules": {
"ngrx/select-style": ["warn", "operator"]
}
```

fix(select-style): simplify and unify settings settings

---

tests/utils/index.ts

A small change that replaces `dist` references on import statement.

refactor: remove `dist` import references

---

.eslintrc.js
package-lock.json
package.json
src/rules/effects/avoid-cyclic-effects.ts
tests/rules/avoid-cyclic-effects.test.ts
tests/rules/prefer-one-generic-in-create-for-feature-selector.test.ts

I just noticed some unused dependencies listed as `devDependencies`. There are:
- `@angular/core`
- `@ngrx/component-store`
- <s>`@ngrx/effects`</s> -> Used in `avoid-cyclic-effects`
- <s>`@ngrx/store`</s> -> Used in `avoid-cyclic-effects`
- `rxjs`
This PR aims to remove them and taking advantage I was looking at this, I decided to update all the other dependencies to the most suitable version (this also solves some high severity vulnerabilities encountered on installation).

fix(avoid-cyclic-effects): warn if ofType has same type as source

---

src/rules/effects/no-effect-decorator.ts
src/rules/effects/prefer-concat-latest-from.ts
src/rules/store/no-typed-global-store.ts
src/rules/store/prefer-inline-action-props.ts
src/rules/store/prefer-one-generic-in-create-for-feature-selector.ts

This will also help to identificate which rules we need to migrate when update to [**`ESLint v8`**](https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.0-released#breaking-changes), where the ~`suggestions`~ `hasSuggestions` will be required for rules that suggest something.

refactor: add missing `suggestion` metadata

---

src/rules/effects/avoid-cyclic-effects.ts
src/rules/effects/no-effect-decorator.ts
src/rules/effects/prefer-concat-latest-from.ts
src/rules/effects/use-effects-lifecycle-interface.ts
src/utils/helper-functions/utils.ts
src/utils/selectors/index.ts
tests/rules/avoid-cyclic-effects.test.ts
tests/rules/no-effect-decorator.test.ts
tests/rules/prefer-concat-latest-from.test.ts
tests/rules/updater-explicit-return-type.test.ts
tests/rules/use-effects-lifecycle-interface.test.ts
tests/rules/use-selector-in-select.test.ts

Currently, the `utils/findBy*` isn't able to handle multiple imports... so when I have something like this:
```ts
import type { Something } from '@ngrx/store'
import { Store } from '@ngrx/store'
```
...the `findNgRxStoreName` returns null as it stops at the first `ImportDeclaration`.
By the way, it was a real situation in an application I was working on, some rules weren't behaving correctly as the imports, like here, are split between type-only and conventional imports 😅 
I've added a test for one rule of each package, LMK if it's sufficient :)

fix: ability to handle multiple imports

---

scripts/generate-config.ts
src/rules/store/avoid-duplicate-actions-in-reducer.ts
src/utils/selectors/index.ts
tests/rules/avoid-duplicate-actions-in-reducer.test.ts

Currently it's checking/reporting duplication on every `createReducer > Identifier`). With the new implementation we collect all the possible duplicate nodes and report it on the `createReducer:exit` as mentioned in #180.
This unintentionally also fixes a possible false positive that is having different reducers controlling actions with the same names :stuck_out_tongue:

fix(avoid-duplicate-actions-in-reducer): simplify

---

src/rules/component-store/updater-explicit-return-type.ts
src/rules/effects/avoid-cyclic-effects.ts
src/rules/store/avoid-combining-selectors.ts
src/rules/store/avoid-mapping-selectors.ts
src/rules/store/prefer-one-generic-in-create-for-feature-selector.ts
src/rules/store/prefix-selectors-with-select.ts
src/utils/selectors/index.ts

**Before**:
**After**:
IMHO, it's much nicer to see what is the content of the select by just hovering it, instead of going to that file.

refactor: use `as const` for selectors

---

src/rules/effects/no-effects-in-providers.ts
src/rules/store/no-reducer-in-key-names.ts
src/utils/selectors/index.ts
tests/rules/no-effects-in-providers.test.ts
tests/rules/no-reducer-in-key-names.test.ts

Currently the rules `no-effects-in-providers` and `no-reducer-in-key-names` aren't capable of looking at `@NgModule` metadata if it's a computed literal or a template literal.

fix: handle literals properly

---

src/rules/store/no-multiple-global-stores.ts
tests/rules/no-multiple-global-stores.test.ts

Currently, if there are multiple classes, this rule reports, even if each constructor has only 1 store.

fix(no-multiple-stores): handle multiple classes properly

---

docs/rules/prefix-selectors-with-select.md
src/rules/store/prefix-selectors-with-select.ts
tests/rules/prefix-selectors-with-select.test.ts

Here's the follow-up PR to handle `createSelectorFactory` as discussed in https://github.com/timdeschryver/eslint-plugin-ngrx/pull/169#discussion_r693381896.
LMK if I'm missing something in the implementation.

feat(prefix-selectors-with-select): add support for `createSelectorFactory`

---

src/rules/store/no-reducer-in-key-names.ts
src/utils/helper-functions/guards.ts
src/utils/helper-functions/utils.ts
src/utils/selectors/index.ts
tests/rules/no-reducer-in-key-names.test.ts

Part of #179.
In addition to adding the suggestion, it fixes a bug introduced by #188. Until then, all `reducers` that contained the word "reducer" would be reported, regardless of where it was inserted. After that, it considered incorrect only the `reducers` that ended with the word "reducer". Unfortunately we didn't have tests that covered this, which is no longer the case now.

feat(no-reducer-in-key-names): add suggestion

---

.eslintrc.js
package.json
scripts/generate-config.ts
scripts/generate-readme.ts
src/configs/index.ts
src/rules/index.ts
src/utils/helper-functions/folder.ts

This enables the rules:
- [**`@typescript-eslint/no-unnecessary-type-assertion`**](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md);
- [**`@typescript-eslint/prefer-reduce-type-parameter`**](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-reduce-type-parameter.md)

build: enable some rules

---

src/rules/store/no-typed-global-store.ts

When we merged #71, we added this comment, but now the issue is closed and it's still not (and I don't think it ever is) safe to offer a fix to this.

refactor(no-typed-global-store): remove outdated comment

---

src/rules/store/select-style.ts
tests/rules/select-style.test.ts

@timdeschryver  I took the liberty of submitting this PR as a draft in an attempt to finally clean up any traces of unused imports.
In a short, it basically lookup for the node import `import { ..., select } from '@ngrx/platform'` and then it grab the references that points to this node. Note that the same approach could be used for `no-effect-creator-and-decorator`, `no-effect-decorator` and `prefer-concat-latest-from`. Let me know what you think.

fix(select-style): remove unused imports after fixing violations

---

src/rules/effects/no-effect-decorator-and-creator.ts
src/rules/effects/no-effect-decorator.ts
src/rules/store/no-multiple-global-stores.ts
src/rules/store/no-reducer-in-key-names.ts
src/rules/store/no-typed-global-store.ts
src/rules/store/on-function-explicit-return-type.ts
src/rules/store/prefer-inline-action-props.ts
src/rules/store/prefer-one-generic-in-create-for-feature-selector.ts
src/rules/store/prefix-selectors-with-select.ts
src/rules/store/use-consistent-global-store-name.ts

Instead of putting `node` + `messageId` in the end, it puts in the begin, which makes it much more readable IMHO.

refactor: organize `context.report` keys

---

src/rules/store/no-reducer-in-key-names.ts
src/utils/helper-functions/utils.ts
tests/rules/no-reducer-in-key-names.test.ts

Instead of using our own implementation, it uses `getPropertyName` from `@typescript-eslint`.

test(no-reducer-in-key-names): ensure the correct behavior for hyphenated keys

---

src/rules/component-store/updater-explicit-return-type.ts
tests/rules/updater-explicit-return-type.test.ts

Part of #242, this fixes the following issues:

fix(updater-explicit-return-type): report nodes beyond `ClassProperty`

---

src/rules/effects/prefer-effect-callback-in-block-statement.ts
src/utils/selectors/index.ts
tests/rules/prefer-effect-callback-in-block-statement.test.ts

Part of #242, this fixes the following issues:

fix(prefer-effect-callback-in-block-statement): handle all kinds of `createEffect` properly

---

tests/rules/avoid-cyclic-effects.test.ts
tests/rules/no-dispatch-in-effects.test.ts
tests/rules/no-multiple-actions-in-effects.test.ts
tests/rules/updater-explicit-return-type.test.ts

Part of #242, this ensures we cover `createEffect` in non `ClassProperties`.

test: ensure the tests cover `createEffect` properly
