timdeschryver/eslint-plugin-ngrx

src/configs/recommended.json
src/rules/index.ts
src/rules/no-typed-store.ts
src/rules/utils/selectors/index.ts
tests/rules/no-typed-store.test.ts

feat: adds no-typed-store rule

---

src/configs/recommended.json
src/rules/avoid-dispatching-multiple-actions-sequentially.ts
src/rules/index.ts
src/rules/utils/selectors/index.ts
tests/rules/avoid-dispatching-multiple-actions-sequentially.test.ts

feat: adds avoid-dispatching-multiple-actions-sequentially rule

---

docs/rules/action-hygiene.md
docs/rules/avoid-dispatching-multiple-actions-sequentially.md
docs/rules/no-dispatch-in-effects.md
docs/rules/no-duplicate-action-in-reducer.md
docs/rules/no-effect-decorator-and-creator.md
docs/rules/no-effect-decorator.md
docs/rules/no-effects-in-providers.md
docs/rules/no-multiple-stores.md
docs/rules/no-typed-store.md
docs/rules/on-function-explicit-return-type.md
docs/rules/use-selector-in-select.md
src/rules/action-hygiene.ts
src/rules/avoid-dispatching-multiple-actions-sequentially.ts
src/rules/no-dispatch-in-effects.ts
src/rules/no-effect-decorator-and-creator.ts
src/rules/no-effect-decorator.ts
src/rules/no-effects-in-providers.ts
src/rules/no-multiple-stores.ts
src/rules/no-typed-store.ts
src/rules/on-function-explicit-return-type.ts
src/rules/use-selector-in-select.ts
src/rules/utils/helper-functions/index.ts
src/rules/utils/index.ts

This is just the setup, the content can be done later when all the rules have been migrated.

feat: setup docs

---

README.md
docs/migrating-from-ngrx-tslint-rules.md
package.json

add general doc in README.md
add migration doc
add README.md to package.json

docs: add general documentation

---

src/rules/avoid-dispatching-multiple-actions-sequentially.ts
tests/rules/avoid-dispatching-multiple-actions-sequentially.test.ts

Fixes https://github.com/timdeschryver/eslint-plugin-ngrx/issues/47.
* added simple test case to validate changes.

fix: add null check to expression evaluation

---

src/rules/action-hygiene.ts
src/utils/selectors/index.ts
tests/rules/action-hygiene.test.ts

Closes #63 (1st commit).
I took the liberty to simplify the condition by moving it to a selector. Let me know if this change is something you would want or not (2nd commit, which can be easily dropped if not necessary).

refactor: change action-hygiene pattern to ensure we report for correct function

---

.eslintrc.js
src/rules/avoid-mapping-selectors.ts
src/rules/no-dispatch-in-effects.ts
src/rules/select-style.ts
src/rules/use-selector-in-select.ts
src/utils/helper-functions/guards.ts
src/utils/helper-functions/settings.ts
src/utils/helper-functions/typecheck.ts
src/utils/selectors/index.ts

refactor(use-selector-in-select): implementation using esquery

---

src/rules/avoid-dispatching-multiple-actions-sequentially.ts
src/utils/selectors/index.ts
tests/rules/avoid-dispatching-multiple-actions-sequentially.test.ts

refactor(avoid-dispatching-multiple-actions-sequentially): use esquery

---

.github/workflows/ci.yml
src/rules/avoid-dispatching-multiple-actions-sequentially.ts
src/utils/selectors/index.ts
tests/rules/avoid-dispatching-multiple-actions-sequentially.test.ts

fix(ngrx-avoid-dispatching-multiple-actions-sequentially): only check violations in their own scope

---

docs/rules/avoid-combining-selectors.md

Change the correct example not to use combineLatest at all

docs(avoid-combining-selectors)

---

docs/rules/no-dispatch-in-effects.md

Sorry for the previous PR, I forgot to pull from the upstream into my forked repo's clone on my computer. This one is normal

Create docs for no-dispatch-in-effects

---

docs/rules/no-dispatch-in-effects.md
docs/rules/no-multiple-actions-in-effects.md

docs: no multiple actions in effects

---

README.md

docs: fix package name in readme

---

src/rules/store/use-selector-in-select.ts
tests/rules/use-selector-in-select.test.ts

fix(use-selector-in-select): allow selectors with string props

---

docs/rules/no-multiple-actions-in-effects.md

examples satisfy prefer-effect-callback-in-block-statement
Also removed "$" from constructor parameters

docs(no-multiple-actions-in-effects): satisfy other rules

---

src/rules/store/avoid-combining-selectors.ts
src/utils/helper-functions/guards.ts
src/utils/selectors/index.ts
tests/rules/avoid-combining-selectors.test.ts

fix(avoid-combining-selectors): detect violation with select pipe

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/documentation.md
src/rules/store/avoid-mapping-selectors.ts
tests/rules/avoid-mapping-selectors.test.ts

fix(avoid-mapping-selectors): only report if used in pipe CallExpression

---

src/rules/store/no-store-subscription.ts
tests/rules/no-store-subscription.test.ts

fix(no-store-subscription): only handle store subscriptions

---

src/rules/store/avoid-mapping-selectors.ts
src/rules/store/no-store-subscription.ts
src/utils/selectors/index.ts
tests/rules/avoid-mapping-selectors.test.ts

fix(avoid-mapping-selectors): report within `pipe` and `select`

---

src/rules/effects/no-effect-decorator-and-creator.ts
src/rules/store/select-style.ts
src/utils/helper-functions/utils.ts
tests/rules/no-effect-decorator-and-creator.test.ts
tests/rules/select-style.test.ts

Here's an attempt to remove the unused imports. PTAL, @timdeschryver :)

 fix: remove unused imports after fix/suggest

---

src/schematics/ng-add/index.ts
tests/schematics/ng-add.test.ts

fix(schematic): don't add the plugin if already added

---

package-lock.json
package.json
src/rules/component-store/updater-explicit-return-type.ts
src/rules/store/on-function-explicit-return-type.ts
src/utils/selectors/index.ts
tests/rules/on-function-explicit-return-type.test.ts

feat(on-function-explicit-return-type): add suggestion

---

.github/workflows/maintenance.yml

ci: add merge conflict label

---

src/rules/component-store/updater-explicit-return-type.ts
src/rules/effects/avoid-cyclic-effects.ts
src/rules/effects/prefer-effect-callback-in-block-statement.ts
src/rules/store/good-action-hygiene.ts
src/rules/store/use-selector-in-select.ts
src/utils/selectors/index.ts

This PR converts some conditionals in form of selector.

refactor: replace some conditionals with selectors

---

src/rules/effects/avoid-cyclic-effects.ts
tests/rules/avoid-cyclic-effects.test.ts

fix(avoid-cyclic-effects): handle `PropertyDeclaration` properly

---

docs/rules/prefer-action-creator-in-dispatch.md
src/rules/store/prefer-action-creator-in-dispatch.ts
src/utils/helper-functions/guards.ts
tests/rules/prefer-action-creator-in-dispatch.test.ts

fix(prefer-action-creator-in-dispatch): properly handle actions with literal objects

---

package-lock.json
package.json
src/schematics/ng-add/index.ts

fix(ng-add): remove comments before parsing

---

src/rules/effects/prefer-concat-latest-from.ts
tests/rules/prefer-concat-latest-from.test.ts

Fixes https://github.com/timdeschryver/eslint-plugin-ngrx/issues/280

fix(prefer-concat-latest-from):  detect multiple arguments

---

src/rules/store/avoid-mapping-selectors.ts
tests/rules/avoid-mapping-selectors.test.ts

fix(avoid-mapping-selectors): allow ThisExpression in map
